import { Resume } from "./types";

export const initialResumeData: Resume = {
  id: "default-resume-1",
  title: "Full Stack Engineer Resume",
  updatedAt: new Date().toISOString(),
  personalInfo: {
    fullName: "Alexander Morgan",
    title: "Senior Full Stack Software Engineer",
    email: "alexander.morgan@example.com",
    phone: "+1 (555) 234-5678",
    location: "San Francisco, CA",
    website: "https://alexmorgan.dev",
    linkedin: "https://linkedin.com/in/alexandermorgan",
    github: "https://github.com/alexmorgan-dev",
    photo: "",
  },
  summary:
    "Results-driven Senior Full Stack Engineer with 6+ years of experience designing, architecting, and scaling high-performance web platforms and distributed microservices. Proven track record of boosting system throughput by 45%, mentoring high-velocity engineering teams, and driving core product innovations using Next.js, TypeScript, React, and Node.js.",
  experience: [
    {
      id: "exp-1",
      jobTitle: "Senior Full Stack Engineer",
      company: "Apex Cloud Technologies",
      location: "San Francisco, CA",
      startDate: "2022-03",
      endDate: "",
      current: true,
      description:
        "• Spearheaded migration of legacy monolith to Next.js App Router and serverless microservices, cutting p95 page latency by 52%.\n• Architected a real-time analytics streaming engine processing 10M+ daily events with Redis and WebSocket pub/sub.\n• Mentored a team of 7 frontend and backend engineers, leading code reviews and driving automated CI/CD pipeline adoption.",
    },
    {
      id: "exp-2",
      jobTitle: "Software Engineer",
      company: "Vanguard Digital Labs",
      location: "Austin, TX",
      startDate: "2019-06",
      endDate: "2022-02",
      current: false,
      description:
        "• Developed reusable React component libraries and design tokens adopted across 4 major customer-facing SaaS products.\n• Optimized PostgreSQL relational schemas and query indices, decreasing average database load by 38%.\n• Collaborated closely with product managers and UX designers to deliver enterprise billing and subscription workflows.",
    },
    {
      id: "exp-3",
      jobTitle: "Junior Frontend Developer",
      company: "Nexus Interactive",
      location: "Austin, TX",
      startDate: "2018-05",
      endDate: "2019-05",
      current: false,
      description:
        "• Implemented accessible responsive user interfaces adhering to WCAG 2.1 AA standards for high-traffic e-commerce clients.\n• Wrote end-to-end integration test suites with Cypress and Jest, boosting code coverage from 60% to 92%.",
    },
  ],
  education: [
    {
      id: "edu-1",
      degree: "B.S. in Computer Science",
      institution: "University of California, Berkeley",
      location: "Berkeley, CA",
      startDate: "2014-08",
      endDate: "2018-05",
      description: "Dean's Honor List, Magna Cum Laude. President of ACM Student Chapter.",
      gpa: "3.85 / 4.0",
    },
  ],
  skills: [
    { id: "sk-1", name: "TypeScript", level: "Expert", category: "Languages" },
    { id: "sk-2", name: "JavaScript (ES6+)", level: "Expert", category: "Languages" },
    { id: "sk-3", name: "React / Next.js", level: "Expert", category: "Frontend" },
    { id: "sk-4", name: "Tailwind CSS", level: "Advanced", category: "Frontend" },
    { id: "sk-5", name: "Node.js / Express", level: "Advanced", category: "Backend" },
    { id: "sk-6", name: "PostgreSQL", level: "Advanced", category: "Database" },
    { id: "sk-7", name: "GraphQL & REST APIs", level: "Advanced", category: "Backend" },
    { id: "sk-8", name: "Docker & Kubernetes", level: "Intermediate", category: "DevOps" },
    { id: "sk-9", name: "AWS (S3, Lambda, RDS)", level: "Advanced", category: "Cloud" },
    { id: "sk-10", name: "Git / CI/CD Actions", level: "Expert", category: "Tools" },
  ],
  projects: [
    {
      id: "proj-1",
      name: "PulseEngine - Real-Time Observability Dashboard",
      description:
        "High-throughput monitoring platform with real-time log ingestion, alert dispatching, and interactive chart visualizations handling 100k requests/sec.",
      technologies: "Next.js, TypeScript, Go, ClickHouse, Tailwind CSS",
      projectUrl: "https://pulseengine.dev",
      githubUrl: "https://github.com/alexmorgan-dev/pulseengine",
      startDate: "2023-01",
      endDate: "2023-08",
    },
    {
      id: "proj-2",
      name: "DevSprint - Collaborative Markdown Workspace",
      description:
        "Collaborative multi-cursor document editor with offline sync, CRDT synchronization, and instant PDF/EPUB export.",
      technologies: "React, WebSockets, Yjs, Zustand, Node.js",
      projectUrl: "https://devsprint.app",
      githubUrl: "https://github.com/alexmorgan-dev/devsprint",
      startDate: "2022-04",
      endDate: "2022-11",
    },
  ],
  certifications: [
    {
      id: "cert-1",
      name: "AWS Certified Solutions Architect – Associate",
      issuer: "Amazon Web Services",
      date: "2023-05",
      url: "https://aws.amazon.com/verification",
    },
    {
      id: "cert-2",
      name: "Meta Front-End Developer Professional Certificate",
      issuer: "Meta / Coursera",
      date: "2021-11",
      url: "https://coursera.org/verify/meta-front-end",
    },
  ],
  languages: [
    { id: "lang-1", name: "English", proficiency: "Native" },
    { id: "lang-2", name: "Spanish", proficiency: "Intermediate" },
    { id: "lang-3", name: "German", proficiency: "Basic" },
  ],
  achievements: [
    {
      id: "ach-1",
      title: "1st Place Winner - Silicon Valley Hackathon 2023",
      description: "Built an AI-driven accessibility tool that transcribes and converts code to audio navigation in real time.",
      date: "2023",
    },
    {
      id: "ach-2",
      title: "Best Open Source Contributor Award",
      description: "Recognized for top contributions to Next.js community libraries with over 20,000 GitHub stars.",
      date: "2022",
    },
  ],
  customSections: [],
  sectionOrder: [
    "summary",
    "experience",
    "education",
    "skills",
    "projects",
    "certifications",
    "languages",
    "achievements",
  ],
  sectionVisibility: {
    summary: true,
    experience: true,
    education: true,
    skills: true,
    projects: true,
    certifications: true,
    languages: true,
    achievements: true,
  },
  settings: {
    template: "modern",
    primaryColor: "#2563eb", // Vibrant Blue
    fontFamily: "inter",
    fontSize: "md",
    spacing: "normal",
    margins: "normal",
    showIcons: true,
  },
};

export const emptyResumeData: Resume = {
  id: "empty-resume",
  title: "Untitled Resume",
  updatedAt: new Date().toISOString(),
  personalInfo: {
    fullName: "",
    title: "",
    email: "",
    phone: "",
    location: "",
    website: "",
    linkedin: "",
    github: "",
    photo: "",
  },
  summary: "",
  experience: [],
  education: [],
  skills: [],
  projects: [],
  certifications: [],
  languages: [],
  achievements: [],
  customSections: [],
  sectionOrder: [
    "summary",
    "experience",
    "education",
    "skills",
    "projects",
    "certifications",
    "languages",
    "achievements",
  ],
  sectionVisibility: {
    summary: true,
    experience: true,
    education: true,
    skills: true,
    projects: true,
    certifications: true,
    languages: true,
    achievements: true,
  },
  settings: {
    template: "modern",
    primaryColor: "#2563eb",
    fontFamily: "inter",
    fontSize: "md",
    spacing: "normal",
    margins: "normal",
    showIcons: true,
  },
};
